// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dhxkgbybiyuoxyuvybsa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRoeGtnYnliaXl1b3h5dXZ5YnNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA5MTY3MzIsImV4cCI6MjA4NjQ5MjczMn0.yoVgf1yK98w8DcDJ49gf0643e2NbNBCNGM7poROLy3Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});